=== jetzz-uwux/ordinatio-ftw/dtd/artefactos.dtd
<!ELEMENT lista-artefactos (set+)>
<!ELEMENT set (nombre, bonificacion-2,bonificacion-4, personajes-recomendados,imagen)>
<!ATTLIST set id ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT bonificacion-2 (#PCDATA)>
<!ELEMENT bonificacion-4 (#PCDATA)>
<!ELEMENT personajes-recomendados (#PCDATA)>
<!ELEMENT imagen (#PCDATA)>

=== jetzz-uwux/ordinatio-ftw/xml/artefactos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lista-artefactos SYSTEM "../dtd/artefactos.dtd">
<lista-artefactos>
    <set id="s1">
        <nombre>Reminiscencia de la Purificación</nombre>
        <bonificacion-2>+18% ATQ</bonificacion-2>
        <bonificacion-4>Potencia Ataques Normales</bonificacion-4>
        <personajes-recomendados>Hu Tao, Yoimiya</personajes-recomendados>
        <imagen>reminiscencia.png</imagen>
    </set>
    <set id="s2">
        <nombre>Emblema del Destino</nombre>
        <bonificacion-2>+20% Recarga de energía</bonificacion-2>
        <bonificacion-4>Potencia Habilidad Definitiva en base a la recarga del personaje</bonificacion-4>
        <personajes-recomendados>Shogun Raiden, Xiangling</personajes-recomendados>
        <imagen>reminiscencia.png</imagen>
    </set>
</lista-artefactos>
