=== jetzz-uwux/ordinatio-ftw/dtd/personajes.dtd
<!ELEMENT lista-personajes (personaje+)>
<!ELEMENT personaje (nombre, rareza, rol, tipo-rol, tipo-arma, afiliacion,descripcion,imagen)>
<!ATTLIST personaje id ID #REQUIRED>
<!ATTLIST personaje elemento CDATA #REQUIRED>
<!ATTLIST personaje region CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT rareza (#PCDATA)>
<!ELEMENT rol (#PCDATA)>
<!ELEMENT tipo-rol (#PCDATA)>
<!ELEMENT tipo-arma (#PCDATA)>
<!ELEMENT afiliacion (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT imagen (#PCDATA)>

=== jetzz-uwux/ordinatio-ftw/xml/personajes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lista-personajes SYSTEM "../dtd/personajes.dtd">
<lista-personajes>
    <personaje id="p1" elemento="Cryo" region="Mondstadt">
        <nombre>Lohen</nombre>
        <rareza>5 estrellas</rareza>
        <rol>DPS</rol>
        <tipo-rol>DPS Principal</tipo-rol>
        <tipo-arma>Lanza</tipo-arma>
        <afiliacion>Caballeros de Favonius</afiliacion>
        <descripcion>Subcapitán de la Compañía de Ofensiva a Distancia de los Caballeros de Favonius, un caballero conocido por su enfoque poco ortodoxo y su predilección por las tácticas poco convencionales.</descripcion>
        <imagen>lohen.png</imagen>
    </personaje>
    <personaje id="p2" elemento="Pyro" region="Liyue">
        <nombre>Hu Tao</nombre>
        <rareza>5 estrellas</rareza>
        <rol>DPS</rol>
        <tipo-rol>DPS Principal</tipo-rol>
        <tipo-arma>Lanza</tipo-arma>
        <afiliacion>Funeraria El Camino</afiliacion>
        <descripcion>77.ª directora de la Funeraria El Camino. Pese a su corta edad, ya es la principal encargada de todos los asuntos funerarios de Liyue.</descripcion>
        <imagen>hutao.png</imagen>
    </personaje>
    <personaje id="p3" elemento="Geo" region="Nod-Krai">
        <nombre>Linnéa</nombre>
        <rareza>5 estrellas</rareza>
        <rol>Sub-DPS, Soporte</rol>
        <tipo-rol>Curador</tipo-rol>
        <tipo-arma>Arco</tipo-arma>
        <afiliacion>Gremio de Aventureros</afiliacion>
        <descripcion>Una asesora del Gremio de Aventureros de Nod Krai y naturalista.</descripcion>
        <imagen>linnea.png</imagen>
    </personaje>
    <personaje id="p4" elemento="Pyro" region="Mondstadt">
        <nombre>Bennett</nombre>
        <rareza>4 estrellas</rareza>
        <rol>Soporte</rol>
        <tipo-rol>Buffer, Curador</tipo-rol>
        <tipo-arma>Espada Ligera</tipo-arma>
        <afiliacion>Gremio de Aventureros</afiliacion>
        <descripcion>El chico aventurero de Mondstadt. Su naturaleza amablae no va acorde su con mala suerte.</descripcion>
        <imagen>bennett.png</imagen>
    </personaje>
    <personaje id="p5" elemento="Electro" region="Inazuma">
        <nombre>Raiden Shogun</nombre>
        <rareza>5 estrellas</rareza>
        <rol>DPS</rol>
        <tipo-rol>DPS Principal</tipo-rol>
        <tipo-arma>Lanza</tipo-arma>
        <afiliacion>Ciudad de Inazuma</afiliacion>
        <descripcion>Su Excelencia, la todopoderosa Narukami, quien té prometió al pueblo de Inazuma la inmutable eternidad.</descripcion>
        <imagen>shogun.png</imagen>
    </personaje>
    <personaje id="p6" elemento="Cryo" region="Sumeru">
        <nombre>Laila</nombre>
        <rareza>4 estrellas</rareza>
        <rol>Soporte</rol>
        <tipo-rol>Escudero</tipo-rol>
        <tipo-arma>Espada Ligera</tipo-arma>
        <afiliacion>Facultad Rtawahist</afiliacion>
        <descripcion>Una estudiante de la Facultad Rtawahist especializada en astrologia teórica, A veces con sonambulismo, otras veces con insomnio, esta chica siempre tiene problemas de sueño.</descripcion>
        <imagen>laila.png</imagen>
    </personaje>
    <personaje id="p7" elemento="Hydro" region="Fontaine">
        <nombre>Furina</nombre>
        <rareza>5 estrellas</rareza>
        <rol>Sub-DPS, Soporte</rol>
        <tipo-rol>Curador</tipo-rol>
        <tipo-arma>Espada Ligera</tipo-arma>
        <afiliacion>Corte de Fontaine</afiliacion>
        <descripcion>El foco de atención absoluto del escenario durante los. juicios, hasta que la obra termina y el público rompe a aplaudir.</descripcion>
        <imagen>furina.png</imagen>
    </personaje>
    <personaje id="p8" elemento="Anemo" region="Natlan">
        <nombre>Chasca</nombre>
        <rareza>5 estrellas</rareza>
        <rol>DPS</rol>
        <tipo-rol>DPS Principal</tipo-rol>
        <tipo-arma>Arco</tipo-arma>
        <afiliacion>Tlalocán</afiliacion>
        <descripcion>La mediadora de Tlalocán, pacificadora de mil conflictos.</descripcion>
        <imagen>chasca.png</imagen>
    </personaje>
    <personaje id="p9" elemento="Dendro" region="Sumeru">
        <nombre>Nahida</nombre>
        <rareza>5 estrellas</rareza>
        <rol>Sub-DPS, Soporte</rol>
        <tipo-rol>Buffer</tipo-rol>
        <tipo-arma>Catalizador</tipo-arma>
        <afiliacion>Ciudad de Sumeru</afiliacion>
        <descripcion>Un pajarito enjaulado en el Santuario Surasthana que solo puede contemplar el mundo desde sus sueños.</descripcion>
        <imagen>nahida.png</imagen>
    </personaje>

</lista-personajes>
